kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build -t my-appp .

  - name: test
    image: node:18
    commands:
      - npm install
      - npm test
